### ISSUE TITLE
Unable to connect to memcached by account username and password?

### ISSUE THREAD

**Issue by du86796922** [bitnami/bitnami-docker-memcached#60]
I created the memcached instance.
Its docker-compose.yaml file

```yaml

version: '2'
services:
  memcached:
    image: 'bitnami/memcached'
    ports:
      - '11211:11211'
    environment:
      - MEMCACHED_USERNAME=root
      - MEMCACHED_PASSWORD=asdasd
```

This is my PHP calling code.

```php

<?php

$memcached = new Memcached();
$memcached->setOption(Memcached::OPT_BINARY_PROTOCOL, true);

$memcached->addServer("192.168.50.165", 11211);
$memcached->setSaslAuthData ("root" , "asdasd");
$memcached->set ("my_user" , "my_password");

var_dump($memcached->get("my_user" ));
```
Cannot connect，
```php
var_dump($memcached->get("my_user" ));#Always return to false

```
I don't know what caused the problem.

This is my PHP extension.

```shell
root@489dcd14d3d7:/# php -v
PHP 7.1.18-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 11 2018 14:22:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

root@489dcd14d3d7:/# php -m
[PHP Modules]
amqp
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
json
libxml
mbstring
mcrypt
memcache
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
rar
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by javsalgar** [comment]
Hi,

Does this `$memcached->setSaslAuthData ("root" , "asdasd");` function return something that can help to debug the issue?

**Comment by aritrac** [comment]
I also want to know what is the default userid and password to login if SASL is enabled. I tried passing the same via docker-compose.yml and also directly via command line, but in both the cases I am not able to connect to the memcached server in the container. Kindly help.

**Comment by javsalgar** [comment]
The default credentials are `root` and empty password. However, could you check inside the container if the file `/opt/bitnami/memcached/data/memcachedsasldb` is created?

**Comment by euclid1990** [comment]
@javsalgar I have same issue, seem default PHP memcached extension not support SASL ? I have try using this image.
docker-compose.yml
```
version: "3.7"

services:
  memcached:
    image: bitnami/memcached:1.5.16
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_USERNAME=my_user
      - MEMCACHED_PASSWORD=my_password
  php:
    image: spacexcn/php-7.0.8-swoole-2
    volumes:
      - .:/var/www/app
    tty: true
```
And I attach into `php` container and run below code:
```
<?php

$mc = new \Memcached();
$mc->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$mc->addServer('memcached', 11211);
var_dump($mc->setSaslAuthData('my_user', 'my_password'));
$mc->set('foo', 'bar');
$value = $mc->get('foo');
var_dump($value);
```
It return
```
bool(true)
bool(false)
```
