### ISSUE TITLE
PASSWORD can't work when run.sh with args

### ISSUE THREAD

**Issue by adevjoe** [bitnami/bitnami-docker-memcached#66]
**Description**

this is my docker-compose.yml, when i set command field, then memcached didn't setup, and the `memcached_enable_authentication` func don't work.
```yaml
version: '2'

services:
  memcached:
    image: 'docker.io/bitnami/memcached:1.6.6-debian-10-r90'
    command: ['/run.sh', '-e/cache-state/memory_file']
    environment:
      - MEMCACHED_USERNAME=admin
      - MEMCACHED_PASSWORD='12345'
    volumes:
      - ./cache-state:/cache-state
    ports:
      - '11211:11211'
```

logs:
```
memcached_1  | memcached 03:11:37.55
memcached_1  | memcached 03:11:37.56 Welcome to the Bitnami memcached container
memcached_1  | memcached 03:11:37.56 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-memcached
memcached_1  | memcached 03:11:37.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-memcached/issues
memcached_1  | memcached 03:11:37.56
memcached_1  |
memcached_1  | memcached 03:11:37.57 INFO  ==> ** Starting Memcached **
memcached_1  | [restart] no metadata save file, starting with a clean cache
```

I think the `entrypoint.sh` don't cover this case.
```sh
if [[ "$*" = "/opt/bitnami/scripts/memcached/run.sh" || "$*" = "/run.sh" ]]; then
    info "** Starting Memcached setup **"
    /opt/bitnami/scripts/memcached/setup.sh
    info "** Memcached setup finished! **"
fi
```

**Describe the results you received:**

PASSWORD can't work

**Describe the results you expected:**

PASSWORD work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: WRBH:C2DZ:3T5Z:KLAQ:JEWN:EZB7:7MMG:B3UI:36LQ:OXPK:X5CF:P7KV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 54
  Goroutines: 62
  System Time: 2020-09-09T03:19:37.5183783Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.1.205:5000
  192.168.99.104:30080
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. The current method to customize the image doesn't allow override the command on that way; as you rightly said, doing that the `setup.sh` is not going to be executed in the `entrypoint.sh` and this file is important to properly configure the application.

Having said that, there is a `MEMCACHED_EXTRA_FLAGS` environment variable that you can use to set more arguments in the `memcached` command, for example
```yaml
 version: '2'

 services:
   memcached:
     image: 'docker.io/bitnami/memcached:1-debian-10'
     environment:
       - MEMCACHED_USERNAME=admin
       - MEMCACHED_PASSWORD='12345'
       - MEMCACHED_EXTRA_FLAGS='-e /cache-state/memory_file'
     ports:
       - '11211:11211'
```

```
$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                  PORTS                      NAMES
39323458437c        bitnami/memcached:1-debian-10   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:11211->11211/tcp   bitnami-docker-memcached_memcached_1

$ dcexec c88
I have no name!@c8862e53d03d:/$ ps xufa
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001         33  2.0  0.0   3868  3184 pts/0    Ss   06:39   0:00 bash
1001         38  0.0  0.0   7640  2724 pts/0    R+   06:39   0:00  \_ ps xufa
1001          1  0.6  0.0 413476  4132 ?        Ssl  06:39   0:00 memcached -u memcached -p 11211 -v -S '-e /cache-state/memory_file'
```

In this case, the container is up and running and checking the process with `ps xufa` the desired flag is set in the command, is this behaviour what you was looking for? Currently, this is the kind of customizations we support regarding the entrypoint and command
