### ISSUE TITLE
Setup will never run due parameter

### ISSUE THREAD

**Issue by cache-sk** [bitnami/bitnami-docker-memcached#70]
**Description**

I'am evaluating bitnami/memcached helm chart, and when I use combination of defined memcachedUsername + memcachedPassword, high-availability architecture and persistence in values, pod(s) starts without sasl enabled - no authentication and no binary protocol. When I get tty/bash to pod and run `ps -ef`, there is missing `-S` argument after memcached.

Helm chart in this combination will generate for memcached image args like this:
```
          args:
            - /run.sh
            - -e/cache-state/memory_file 
```
(Which is bug too I assume, missing space between `-e` and `/cache-state/memory_file` - will open ~PR~ issue there)

After tracking through scripts, I think that `setup.sh` is never executed in `entrypoint.sh`, thus `memcached_initialize` is never called and `memcached_enable_authentication` will never generate `SASL_CONF_FILE` so `run.sh` will not add '-S' argument.

Probably because `/run.sh -e/cache-state/memory_file` will not match `if [[ "$*" = "/opt/bitnami/scripts/memcached/run.sh" || "$*" = "/run.sh" ]]; then` condition.

Maybe use of `$0` instead of `$*` will fix it, but I am no expert in shell scripting :)

**Steps to reproduce the issue:**

`helm install test-memcached bitnami/memcached -f values.yaml`

values.yaml:
```
memcachedUsername: admin
memcachedPassword: adminpass
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    memory: 256Mi
    cpu: 50m
persistence:
  enabled: true
  size: 512Mi
architecture: "high-availability"
extraEnv:
  - name: "MEMCACHED_CACHE_SIZE"
    value: "480"
```

**Describe the results you expected:**

Helm chart will deploy memcached correctly with auth, HA and persistence.
